### ISSUE TITLE
Setup Prometheus

### ISSUE THREAD

**Issue by mirbitu** [MinitwitGroupI/MiniTwit#69]
setup prometheus to read metrics from /metrics

**Comment by anderslatif** [comment]
I've started working on this.

**Comment by anderslatif** [comment]
#80 
First half is done which is the implementation in our server. 
Next step is the integration which involves creating a container for it. 
I have started working on the task in this branch:

https://github.com/MinitwitGroupI/MiniTwit/tree/setup-prometheus-container

But I am running into this problem:

<img width="1334" alt="Screenshot 2023-03-09 at 03 01 13" src="https://user-images.githubusercontent.com/7512403/223896376-79faaabf-3835-4ab7-9abb-0fae73d8c4d0.png">

I am not sure if I need to import the prometheus yaml file into the container somehow. 
The error message is also odd because it mentions mac but I am running everything inside a Docker container. 
Someone smarter can help out.

**Comment by anderslatif** [comment]
#79 #80
